### ISSUE TITLE
Question: Is there any reason why the :sessionize:app module is in Multiplatform?

### ISSUE THREAD

**Issue by archiegq21** [touchlab/DroidconKotlin#140]
Just wondering why the sessionize module was configured as a Multiplatform Module. It seems to me that it could simply be a normal android application. Is there any special reason for this?

**Comment by kpgalligan** [comment]
Because it also builds as an iOS application. That's essentially the point of the repo. It was one of the first public, full KMP/KMM applications. The `iosApp` folder has an iOS application, which points to the shared module here: https://github.com/touchlab/DroidconKotlin/blob/master/iosApp/Podfile#L16

**Comment by kpgalligan** [comment]
Example: https://apps.apple.com/us/app/droidcon-nyc-2019/id1477469914

**Comment by archiegq21** [comment]
Hi @kpgalligan thanks for the explanation but doesn't the `iosApp` only reference the `:sessionize:lib` module only? and so the `app` module doesn't have to be `KMM`? (At this point I realized that I reference the `sessionize` as a module instead of the `:app` module...

**Comment by kpgalligan** [comment]
Ah, yes. `app` does not need to be a KMP module. Historical reasons I assume. There were some commits from 2020, but this really hasn't had any serious attention since 2019, and that basic module layout has existed since 2018, which is ancient for KMP. I assume that was working around some dependency issue at the time.

**Comment by archiegq21** [comment]
Would you be okay if I make the PR to make convert to a simple android application? or would you rather keep the current way it was configured?

**Comment by kpgalligan** [comment]
Sorry, missed this. PR would be fine, if interested.
